.Dd December 25, 2020
.Dt banter 1
.Os
.
.Sh NAME
.Nm banter
.Nd little script to make irc color art that will probably get you banned 
.
.Sh SYNOPSIS
.Nm
.Ar file
.Op Ar delay
.
.Sh DESCRIPTION
.Nm
is a image to irc color codes converter.
.Pp
note that if the color changes too rapidly and
other factors like a long channel name and short
line length may cause one line of pixels to continue
to the next line, ruining the image
.
.Sh OPTIONS
